# Generated by Django 5.1.1 on 2024-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
